### ISSUE TITLE
refactor scraping script to use multithreading

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/fake-news-detection#2]
This will make the scraping script quicker, making it easier to collect large amounts of data. Asyncio may be the best option for this, but open to other options.

**Comment by SalimNhiri** [comment]
Hi @raspberri05, 
I am happy to contribute, can you please assign me for #2.
Let me know if you have additional info about this issue

**Comment by raspberri05** [comment]
Hi, I managed to fix the issue yesterday but forgot to close it. This issue is no longer available
